projects:
  rekuest:
    schema: http://localhost:8090/graphql
    documents: graphql/*/**.graphql
    extensions:
      turms:
        out_dir: rekuest/api
        always_resolve_interfaces: True
        freeze: True
        parsers:
          - type: turms.parsers.polyfill.PolyfillParser
            python_version: 3.7
        stylers:
          - type: turms.stylers.default.DefaultStyler
          - type: turms.stylers.appender.AppenderStyler
            append_fragment: "Fragment"
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
          - type: turms.plugins.funcs.FuncsPlugin
            global_kwargs:
              - type: rekuest.rath.RekuestRath
                key: rath
                description: "The arkitekt rath client"
            definitions:
              - type: subscription
                is_async: True
                use: rekuest.funcs.asubscribe
              - type: query
                is_async: True
                use: rekuest.funcs.aexecute
              - type: mutation
                is_async: True
                use: rekuest.funcs.aexecute
              - type: subscription
                use: rekuest.funcs.subscribe
              - type: query
                use: rekuest.funcs.execute
              - type: mutation
                use: rekuest.funcs.execute
        processors:
          - type: turms.processors.black.BlackProcessor
        scalar_definitions:
          uuid: str
          Callback: str
          Any: typing.Any
          AnyInput: typing.Any
          QString: rekuest.scalars.QString
          ID: rath.scalars.ID
          Identifier: rekuest.scalars.Identifier
        additional_bases:
          Node:
            - rekuest.traits.node.Reserve
          ArgPortInput:
            - rekuest.traits.ports.PortInput
