""" This file was code generated by turms. If you want to change the contents of this file, you should make sure to add the MergeProcessor to your config will keep your changes when you re-run turms)."""
    
from arkitekt_spec.actions import ActionDemandInput, ActionKind, AgentDependencyInput, AssignWidgetInput, ComponentNodeInput, ImplementationInput, PortKind, PortMatchInput, ReturnWidgetInput, StateDemandInput
from datetime import datetime
from enum import Enum
from pydantic import AliasChoices, BaseModel, ConfigDict, Field
from rath.scalars import ID
from rekuest.scalars import ActionHash, Args, Identifier, MediaLike
from rekuest.traits.blok import CreateBlokInputTrait
from typing import Annotated

class GraphQLDefault:
    """Records a GraphQL field schema default value. The client omits the field so the server applies its own default; this preserves the value for introspection."""

    def __init__(self, value):
        self.value = value

    def __repr__(self):
        return 'GraphQLDefault(' + repr(self.value) + ')'

class AgentKind(str, Enum):
    """No documentation"""
    WEBSOCKET = 'WEBSOCKET'
    WEBHOOK = 'WEBHOOK'
    __str__ = str.__str__

class AssignWidgetKind(str, Enum):
    """The kind of assign widget."""
    SEARCH = 'SEARCH'
    CHOICE = 'CHOICE'
    SLIDER = 'SLIDER'
    CUSTOM = 'CUSTOM'
    STRING = 'STRING'
    STATE_CHOICE = 'STATE_CHOICE'
    PROXY = 'PROXY'
    __str__ = str.__str__

class CatalogValueKind(str, Enum):
    """The kind of value a catalog component prop accepts or a catalog operation argument/return carries."""
    STRING = 'STRING'
    INT = 'INT'
    FLOAT = 'FLOAT'
    BOOL = 'BOOL'
    DICT = 'DICT'
    LIST = 'LIST'
    ANY = 'ANY'
    CALLBACK = 'CALLBACK'
    __str__ = str.__str__

class DemandKind(str, Enum):
    """No documentation"""
    ARGS = 'ARGS'
    RETURNS = 'RETURNS'
    __str__ = str.__str__

class DiagnosticLevel(str, Enum):
    """Severity of a registration finding. Errors are never stored (they abort registration), so only WARNING exists."""
    WARNING = 'WARNING'
    __str__ = str.__str__

class HookKind(str, Enum):
    """No documentation"""
    CLEANUP = 'CLEANUP'
    INIT = 'INIT'
    __str__ = str.__str__

class LogLevel(str, Enum):
    """No documentation"""
    DEBUG = 'DEBUG'
    INFO = 'INFO'
    ERROR = 'ERROR'
    WARN = 'WARN'
    CRITICAL = 'CRITICAL'
    __str__ = str.__str__

class Ordering(str, Enum):
    """No documentation"""
    ASC = 'ASC'
    ASC_NULLS_FIRST = 'ASC_NULLS_FIRST'
    ASC_NULLS_LAST = 'ASC_NULLS_LAST'
    DESC = 'DESC'
    DESC_NULLS_FIRST = 'DESC_NULLS_FIRST'
    DESC_NULLS_LAST = 'DESC_NULLS_LAST'
    __str__ = str.__str__

class ReturnWidgetKind(str, Enum):
    """The kind of return widget."""
    CHOICE = 'CHOICE'
    CUSTOM = 'CUSTOM'
    __str__ = str.__str__

class TaskEventKind(str, Enum):
    """The event kind of the taskevent"""
    BOUND = 'BOUND'
    QUEUED = 'QUEUED'
    STARTED = 'STARTED'
    PROGRESS = 'PROGRESS'
    DELEGATE = 'DELEGATE'
    UNASSIGN = 'UNASSIGN'
    DISCONNECTED = 'DISCONNECTED'
    YIELD = 'YIELD'
    COMPLETED = 'COMPLETED'
    LOG = 'LOG'
    CANCELLING = 'CANCELLING'
    CANCELLED = 'CANCELLED'
    INTERRUPTING = 'INTERRUPTING'
    INTERRUPTED = 'INTERRUPTED'
    PAUSING = 'PAUSING'
    PAUSED = 'PAUSED'
    RESUMING = 'RESUMING'
    RESUMED = 'RESUMED'
    FAILED = 'FAILED'
    CRITICAL = 'CRITICAL'
    __str__ = str.__str__

class TaskInstructKind(str, Enum):
    """The event kind of the taskevent"""
    ASSIGN = 'ASSIGN'
    CANCEL = 'CANCEL'
    RESUME = 'RESUME'
    PAUSE = 'PAUSE'
    INTERRUPT = 'INTERRUPT'
    COLLECT = 'COLLECT'
    __str__ = str.__str__

class ActionFilter(BaseModel):
    """No documentation"""
    name: 'StrFilterLookup | None' = None
    and_: 'ActionFilter | None' = Field(validation_alias=AliasChoices('and_', 'AND'), serialization_alias='AND', default=None)
    or_: 'ActionFilter | None' = Field(validation_alias=AliasChoices('or_', 'OR'), serialization_alias='OR', default=None)
    not_: 'ActionFilter | None' = Field(validation_alias=AliasChoices('not_', 'NOT'), serialization_alias='NOT', default=None)
    distinct: bool | None = Field(validation_alias=AliasChoices('distinct', 'DISTINCT'), serialization_alias='DISTINCT', default=None)
    search: str | None = Field(default=None, description="Search by name: a case-insensitive substring, or semantic similarity of the query to the action's name and description. Substring matches rank first, then by similarity; an explicit `ordering` replaces that ranking.")
    ids: tuple[ID, ...] | None = None
    demands: tuple['PortDemandInput', ...] | None = None
    object_demands: tuple['PortDemandInput', ...] | None = Field(validation_alias=AliasChoices('object_demands', 'objectDemands'), serialization_alias='objectDemands', default=None)
    protocols: tuple[str, ...] | None = None
    kind: ActionKind | None = None
    in_collection: str | None = Field(validation_alias=AliasChoices('in_collection', 'inCollection'), serialization_alias='inCollection', default=None)
    used_before: datetime | None = Field(validation_alias=AliasChoices('used_before', 'usedBefore'), serialization_alias='usedBefore', default=None)
    used_after: datetime | None = Field(validation_alias=AliasChoices('used_after', 'usedAfter'), serialization_alias='usedAfter', default=None)
    stateful: bool | None = None
    app_identifier: str | None = Field(validation_alias=AliasChoices('app_identifier', 'appIdentifier'), serialization_alias='appIdentifier', default=None, description='Filter using app identifier')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ActionOrderDefinedAt(BaseModel):
    """'definedAt' variant of the @oneOf input 'ActionOrder'"""
    defined_at: Ordering = Field(validation_alias=AliasChoices('defined_at', 'definedAt'), serialization_alias='definedAt')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ActionOrderUsedAt(BaseModel):
    """'usedAt' variant of the @oneOf input 'ActionOrder'"""
    used_at: Ordering = Field(validation_alias=AliasChoices('used_at', 'usedAt'), serialization_alias='usedAt')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)
ActionOrder = ActionOrderDefinedAt | ActionOrderUsedAt

class AgentFilter(BaseModel):
    """A way to filter agents"""
    and_: 'AgentFilter | None' = Field(validation_alias=AliasChoices('and_', 'AND'), serialization_alias='AND', default=None)
    or_: 'AgentFilter | None' = Field(validation_alias=AliasChoices('or_', 'OR'), serialization_alias='OR', default=None)
    not_: 'AgentFilter | None' = Field(validation_alias=AliasChoices('not_', 'NOT'), serialization_alias='NOT', default=None)
    distinct: bool | None = Field(validation_alias=AliasChoices('distinct', 'DISTINCT'), serialization_alias='DISTINCT', default=None)
    client_id: str | None = Field(validation_alias=AliasChoices('client_id', 'clientId'), serialization_alias='clientId', default=None, description='Filter by client ID of the app the agent is registered to')
    ids: tuple[ID, ...] | None = Field(default=None, description='Filter by IDs of the agents')
    has_implementations: tuple[str, ...] | None = Field(validation_alias=AliasChoices('has_implementations', 'hasImplementations'), serialization_alias='hasImplementations', default=None, description='Filter by implementations of the agents')
    has_states: tuple[str, ...] | None = Field(validation_alias=AliasChoices('has_states', 'hasStates'), serialization_alias='hasStates', default=None, description='Filter by states of the agents')
    pinned: bool | None = Field(default=None, description='Filter by pinned agents')
    search: str | None = Field(default=None, description='Filter by name of the agents')
    dependency: ID | None = None
    blok_dependency: ID | None = Field(validation_alias=AliasChoices('blok_dependency', 'blokDependency'), serialization_alias='blokDependency', default=None)
    three_d_model: ID | None = Field(validation_alias=AliasChoices('three_d_model', 'threeDModel'), serialization_alias='threeDModel', default=None)
    distinct: bool | None = None
    action_demands: tuple[ActionDemandInput, ...] | None = Field(validation_alias=AliasChoices('action_demands', 'actionDemands'), serialization_alias='actionDemands', default=None)
    state_demands: tuple[StateDemandInput, ...] | None = Field(validation_alias=AliasChoices('state_demands', 'stateDemands'), serialization_alias='stateDemands', default=None)
    user: ID | None = Field(default=None, description='Filter by user ID')
    app_identifier: ID | None = Field(validation_alias=AliasChoices('app_identifier', 'appIdentifier'), serialization_alias='appIdentifier', default=None, description='Filter using app identifier')
    version_number: str | None = Field(validation_alias=AliasChoices('version_number', 'versionNumber'), serialization_alias='versionNumber', default=None, description='Filter based on version string')
    device_id: ID | None = Field(validation_alias=AliasChoices('device_id', 'deviceId'), serialization_alias='deviceId', default=None, description='Filter based on device')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class AgentInput(BaseModel):
    """No documentation"""
    name: str | None = Field(default=None, description='The name of the agent. This is used to identify the agent in the system.')
    description: str | None = Field(default=None, description='What this agent is, in a sentence. Omitting it leaves whatever the agent already has: a name is what identifies it, a description is what tells two of them apart.')
    kind: AgentKind | None = Field(default=None, description='The transport kind of the agent: WEBSOCKET (default) or WEBHOOK (a HookAgent the backend POSTs to).')
    hook_url: str | None = Field(validation_alias=AliasChoices('hook_url', 'hookUrl'), serialization_alias='hookUrl', default=None, description='For a WEBHOOK agent: the URL the backend POSTs messages (Assign, Cancel, Caller* events) to.')
    hook_url_secret: str | None = Field(validation_alias=AliasChoices('hook_url_secret', 'hookUrlSecret'), serialization_alias='hookUrlSecret', default=None, description='For a WEBHOOK agent: the shared secret used to HMAC-sign messages in both directions (outbound delivery and POST intake).')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class AssignInput(BaseModel):
    """The input for assigning args to a action. A GraphQL assign is a ROOT by definition — children are created only over the agent socket (AssignRequest, where parent is mandatory) and by server-internal paths like init hooks, so parent/dependency/method are deliberately absent here."""
    action: ID | None = Field(default=None, description='The action ID to assign to')
    resolution: ID | None = Field(default=None, description='The resolution ID to assign to when assining to a implementation with dependencies')
    implementation: ID | None = Field(default=None, description='The implementation ID to assign to when directly assingint to a implementation')
    agent: ID | None = Field(default=None, description='The agent ID to assign to when directly assingint to a implementation')
    action_hash: ActionHash | None = Field(validation_alias=AliasChoices('action_hash', 'actionHash'), serialization_alias='actionHash', default=None, description='The hash of the action. This is used to identify the action in the system.')
    interface: str | None = Field(default=None, description='The interface of the implementation. Only ussable if you also set agent')
    hooks: tuple['HookInput', ...] | None = Field(default=None, description='The hooks of the task. This is used to identify the task in the system.')
    args: Args = Field(description='The args of the task. Its a dictionary of ports and values')
    reference: str | None = Field(default=None, description='The reference of the task. This is used to identify the task in the system.')
    capture: bool = Field(description='Whether to capture the task.')
    dependencies: tuple['ResolvedDependencyInput', ...] | None = Field(default=None, description='The dependencies of the task. This maps dependency keys to implementation IDs.')
    step: bool | None = Field(default=None, description='Whether the task should step. Ie. go to the next breakpoint')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class BlokAgentMappingInput(BaseModel):
    """The input for updating a blok."""
    agent: ID
    key: str
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CancelInput(BaseModel):
    """The input for canceling a task."""
    task: ID = Field(description='The task ID to cancel')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CatalogArgumentInput(BaseModel):
    """An argument a catalog operation accepts."""
    key: str = Field(description='The argument key a UtilCall argument must use.')
    kind: CatalogValueKind = Field(description='The value kind of the argument.')
    required: Annotated[bool | None, GraphQLDefault('True')] = Field(default=None, description='Whether every call must pass this argument.')
    'Whether every call must pass this argument.\nDefault: True'
    description: str | None = Field(default=None, description='Human-readable description of the argument.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CatalogComponentInput(BaseModel):
    """A component a UI catalog can render."""
    name: str = Field(description="The component name a ComponentNode.component (or a custom widget's component) must match.")
    description: str | None = Field(default=None, description='Human-readable description of the component.')
    props: Annotated[tuple['CatalogPropInput', ...] | None, GraphQLDefault('[]')] = Field(default=None, description='The props this component accepts.')
    'The props this component accepts.\nDefault: []'
    accepts_children: Annotated[bool | None, GraphQLDefault('True')] = Field(validation_alias=AliasChoices('accepts_children', 'acceptsChildren'), serialization_alias='acceptsChildren', default=None, description='Whether ComponentNode.children may be nested under this component.')
    'Whether ComponentNode.children may be nested under this component.\nDefault: True'
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CatalogOperationInput(BaseModel):
    """A pure operation a UI catalog can evaluate for UtilCalls."""
    name: str = Field(description='The operation name a UtilCall.operation must match.')
    description: str | None = Field(default=None, description='Human-readable description of the operation.')
    arguments: Annotated[tuple[CatalogArgumentInput, ...] | None, GraphQLDefault('[]')] = Field(default=None, description='The arguments the operation accepts.')
    'The arguments the operation accepts.\nDefault: []'
    returns: CatalogValueKind = Field(description='The kind of value the operation returns (BOOL for effect and validator calls).')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CatalogPropInput(BaseModel):
    """A prop a catalog component accepts."""
    key: str = Field(description='The prop key a ComponentProp.key must match.')
    kind: CatalogValueKind = Field(description='The value kind this prop accepts. CALLBACK props must be bound via agent_call or util_call.')
    required: Annotated[bool | None, GraphQLDefault('False')] = Field(default=None, description='Whether every component instance must set this prop.')
    'Whether every component instance must set this prop.\nDefault: False'
    description: str | None = Field(default=None, description='Human-readable description of the prop.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CollectInput(BaseModel):
    """The input for collecting a shelved item in a drawer."""
    drawers: tuple[ID, ...] = Field(description='The drawer ID to collect')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CreateBlokInput(CreateBlokInputTrait, BaseModel):
    """The input for creating a blok."""
    name: str = Field(description='The name of the Blok, used for identification in the system.')
    dependencies: tuple[AgentDependencyInput, ...] | None = Field(default=None, description='The dependencies of the blok. This is used to identify the blok in the system.')
    description: str | None = Field(default=None, description='The description of the blok. This can described the blok and its purpose.')
    catalog: str | None = Field(default=None, description='The universal id')
    components: tuple[ComponentNodeInput, ...] | None = Field(default=None, description='The schema of the blok. This can be used to validate the blok input and output.')
    demo_state: Args | None = Field(validation_alias=AliasChoices('demo_state', 'demoState'), serialization_alias='demoState', default=None, description='The initial state of the blok. This is used to set the initial state of the blok when it is materialized.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CreateDashboardInput(BaseModel):
    """Input for creating a dashboard, optionally specifying its name and the bloks to include. It is owned by the caller's organization."""
    name: str = Field(description='The name of the dashboard.')
    bloks: Annotated[tuple[str, ...] | None, GraphQLDefault('[]')] = Field(default=None, description='The list of blok IDs to include in the dashboard.')
    'The list of blok IDs to include in the dashboard.\nDefault: []'
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CreateImplementationInput(BaseModel):
    """The input for creating a implementation."""
    implementation: ImplementationInput = Field(description='The implementation to create. This is used to identify the implementation in the system.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CreateShortcutInput(BaseModel):
    """The input for creating a shortcut."""
    name: str = Field(description='The name of the shortcut. This is used to identify the shortcut in the system.')
    description: str | None = Field(default=None, description='The description of the shortcut.This can described the shortcut and its purpose.')
    action: ID = Field(description='The action ID to create a shortcut for')
    args: Args = Field(description='The arguments to pre-pass to the shortcut. This is used to identify the shortcut in the system.')
    allow_quick: Annotated[bool | None, GraphQLDefault('False')] = Field(validation_alias=AliasChoices('allow_quick', 'allowQuick'), serialization_alias='allowQuick', default=None, description='Whether to allow quick shortcuts. Quick shorts are shortcuts that can be autorun without scpeific assignment')
    'Whether to allow quick shortcuts. Quick shorts are shortcuts that can be autorun without scpeific assignment\nDefault: False'
    use_returns: Annotated[bool | None, GraphQLDefault('False')] = Field(validation_alias=AliasChoices('use_returns', 'useReturns'), serialization_alias='useReturns', default=None, description='Whether when running the short the returns should be used further. Allows to create mini pipelines')
    'Whether when running the short the returns should be used further. Allows to create mini pipelines\nDefault: False'
    bind_number: int | None = Field(validation_alias=AliasChoices('bind_number', 'bindNumber'), serialization_alias='bindNumber', default=None, description='The bind number of the shortcut. This is used to identify the shortcut in the system.')
    toolbox: ID | None = Field(default=None, description='The toolbox ID to create the shortcut in. If not provided, the shortcut will be created in the default toolbox.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CreateSpaceInput(BaseModel):
    """The input for creating a space."""
    name: str = Field(description='The name of the space. This is used to identify the space in the system.')
    placements: tuple['PlacementInput', ...] | None = Field(default=None, description='The placements to create in the space. This is used to identify the placements in the system.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CreateTestCaseInput(BaseModel):
    """No documentation"""
    action: ID
    tester: ID
    description: str | None = None
    name: str | None = None
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CreateTestResultInput(BaseModel):
    """No documentation"""
    case: ID
    tester: ID
    implementation: ID
    passed: bool
    result: str | None = None
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class CreateThreeDModelInput(BaseModel):
    """The input for creating a 3D model."""
    name: str = Field(description='The name of the 3D model.')
    description: str | None = Field(default=None, description='A description of the 3D model.')
    media: MediaLike = Field(description='The media store file for the 3D model.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class FinishMediaUploadInput(BaseModel):
    """No documentation"""
    store_id: str = Field(validation_alias=AliasChoices('store_id', 'storeId'), serialization_alias='storeId')
    valid: Annotated[bool | None, GraphQLDefault('True')] = None
    'Default: True'
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class HookInput(BaseModel):
    """A hook is a function that is called when a action has reached a specific lifecycle point. Hooks are jsut actions that take a task as input and return a value."""
    kind: HookKind = Field(description='The kind of the hook. This is used to identify the hook in the system.')
    hash: ActionHash = Field(description='The hash of the hook. This is used to identify the hook in the system.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ImplementationActionFilter(BaseModel):
    """No documentation"""
    and_: 'ImplementationActionFilter | None' = Field(validation_alias=AliasChoices('and_', 'AND'), serialization_alias='AND', default=None)
    or_: 'ImplementationActionFilter | None' = Field(validation_alias=AliasChoices('or_', 'OR'), serialization_alias='OR', default=None)
    not_: 'ImplementationActionFilter | None' = Field(validation_alias=AliasChoices('not_', 'NOT'), serialization_alias='NOT', default=None)
    distinct: bool | None = Field(validation_alias=AliasChoices('distinct', 'DISTINCT'), serialization_alias='DISTINCT', default=None)
    search: str | None = None
    name: str | None = None
    ids: tuple[ID, ...] | None = None
    demands: tuple['PortDemandInput', ...] | None = None
    kind: ActionKind | None = None
    protocols: tuple[str, ...] | None = None
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ImplementationAgentFilter(BaseModel):
    """No documentation"""
    and_: 'ImplementationAgentFilter | None' = Field(validation_alias=AliasChoices('and_', 'AND'), serialization_alias='AND', default=None)
    or_: 'ImplementationAgentFilter | None' = Field(validation_alias=AliasChoices('or_', 'OR'), serialization_alias='OR', default=None)
    not_: 'ImplementationAgentFilter | None' = Field(validation_alias=AliasChoices('not_', 'NOT'), serialization_alias='NOT', default=None)
    distinct: bool | None = Field(validation_alias=AliasChoices('distinct', 'DISTINCT'), serialization_alias='DISTINCT', default=None)
    client_id: str | None = Field(validation_alias=AliasChoices('client_id', 'clientId'), serialization_alias='clientId', default=None)
    ids: tuple[ID, ...] | None = None
    has_implementations: tuple[str, ...] | None = Field(validation_alias=AliasChoices('has_implementations', 'hasImplementations'), serialization_alias='hasImplementations', default=None)
    has_states: tuple[str, ...] | None = Field(validation_alias=AliasChoices('has_states', 'hasStates'), serialization_alias='hasStates', default=None)
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ImplementationFilter(BaseModel):
    """No documentation"""
    interface: 'StrFilterLookup | None' = None
    action: ImplementationActionFilter | None = None
    agent: ImplementationAgentFilter | None = None
    and_: 'ImplementationFilter | None' = Field(validation_alias=AliasChoices('and_', 'AND'), serialization_alias='AND', default=None)
    or_: 'ImplementationFilter | None' = Field(validation_alias=AliasChoices('or_', 'OR'), serialization_alias='OR', default=None)
    not_: 'ImplementationFilter | None' = Field(validation_alias=AliasChoices('not_', 'NOT'), serialization_alias='NOT', default=None)
    distinct: bool | None = Field(validation_alias=AliasChoices('distinct', 'DISTINCT'), serialization_alias='DISTINCT', default=None)
    active: bool | None = None
    ids: tuple[ID, ...] | None = None
    action_hash: ActionHash | None = Field(validation_alias=AliasChoices('action_hash', 'actionHash'), serialization_alias='actionHash', default=None)
    parameters: tuple['ParamPair', ...] | None = None
    resolvable_for: ID | None = Field(validation_alias=AliasChoices('resolvable_for', 'resolvableFor'), serialization_alias='resolvableFor', default=None)
    search: str | None = None
    action_demand: ActionDemandInput | None = Field(validation_alias=AliasChoices('action_demand', 'actionDemand'), serialization_alias='actionDemand', default=None)
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class InterruptInput(BaseModel):
    """The input for interrupting a task."""
    task: ID = Field(description='The task ID to interrupt')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class MappedAgentInput(BaseModel):
    """The input for mapping actions to implementations in a agent."""
    key: str = Field(description='The key of the agent to map. This is used to identify the agent in the system.')
    agent: ID = Field(description='The agent ID to map the actions to. This is used to identify the agent in the system.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class MaterializeBlokInput(BaseModel):
    """The input for creating a blok."""
    blok: ID
    dashboard: ID | None = Field(default=None, description='The dashboard ID to materialize the blok in. If not provided, the blok will be materialized in the default dashboard.')
    agent_mappings: tuple[BlokAgentMappingInput, ...] | None = Field(validation_alias=AliasChoices('agent_mappings', 'agentMappings'), serialization_alias='agentMappings', default=None, description='The agent mappings for the blok. This is used to map the blok dependencies to agents in the system.')
    name: str | None = Field(default=None, description="Display name of this materialization. Defaults to the blok's name.")
    description: str | None = Field(default=None, description="Description of this materialization. Defaults to the blok's description.")
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class OffsetPaginationInput(BaseModel):
    """No documentation"""
    offset: Annotated[int | None, GraphQLDefault('0')] = None
    'Default: 0'
    limit: int | None = None
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ParamPair(BaseModel):
    """No documentation"""
    key: str
    value: str
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class PauseInput(BaseModel):
    """The input for pausing a task."""
    task: ID = Field(description='The task ID to pause')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class PlacementInput(BaseModel):
    """The input for creating or updating a placement."""
    role: str | None = Field(default=None, description='The role of the placement. This is used to identify the placement in the system.')
    affine_matrix: tuple[tuple[float, ...], ...] | None = Field(validation_alias=AliasChoices('affine_matrix', 'affineMatrix'), serialization_alias='affineMatrix', default=None, description='The affine matrix for the placement. This is used to identify the placement in the system.')
    model: ID | None = Field(default=None, description='The 3D model ID for the placement. This is used to identify the 3D model in the system.')
    agent: ID | None = Field(default=None, description='The agent ID for the placement. This is used to identify the agent in the system.')
    blok: ID | None = Field(default=None, description='A specific blok that should be used to visualize the state of the placement.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class PortDemandInput(BaseModel):
    """The input for creating a port demand."""
    kind: DemandKind = Field(description='The kind of the demand. You can ask for args or returns')
    matches: tuple[PortMatchInput, ...] | None = Field(default=None, description='The matches of the demand. ')
    force_length: int | None = Field(validation_alias=AliasChoices('force_length', 'forceLength'), serialization_alias='forceLength', default=None, description='Require that the action has a specific number of ports. This is used to identify the demand in the system.')
    force_non_nullable_length: int | None = Field(validation_alias=AliasChoices('force_non_nullable_length', 'forceNonNullableLength'), serialization_alias='forceNonNullableLength', default=None, description='Require that the action has a specific number of non-nullable ports. This is used to identify the demand in the system.')
    force_structure_length: int | None = Field(validation_alias=AliasChoices('force_structure_length', 'forceStructureLength'), serialization_alias='forceStructureLength', default=None, description='Require that the action has a specific number of structure ports. This is used to identify the demand in the system.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class RegisterUiCatalogInput(BaseModel):
    """Register (upsert by name, scoped to the caller's organization) the components and operations a UI app can render and evaluate."""
    name: str = Field(description='The catalog name. Bloks and definitions reference it by this name; registering again replaces the previous components and operations.')
    description: str | None = Field(default=None, description='Human-readable description of the catalog.')
    components: Annotated[tuple[CatalogComponentInput, ...] | None, GraphQLDefault('[]')] = Field(default=None, description='The components this catalog can render.')
    'The components this catalog can render.\nDefault: []'
    operations: Annotated[tuple[CatalogOperationInput, ...] | None, GraphQLDefault('[]')] = Field(default=None, description='The pure operations this catalog can evaluate for UtilCalls.')
    'The pure operations this catalog can evaluate for UtilCalls.\nDefault: []'
    widget_defaults: Annotated[tuple['WidgetDefaultInput', ...] | None, GraphQLDefault('[]')] = Field(validation_alias=AliasChoices('widget_defaults', 'widgetDefaults'), serialization_alias='widgetDefaults', default=None, description='Default widgets per port kind and/or structure identifier. A UI renders them for ports that declare no widget; an identifier match beats a kind match. Each widget is validated against this catalog plus base at registration.')
    'Default widgets per port kind and/or structure identifier. A UI renders them for ports that declare no widget; an identifier match beats a kind match. Each widget is validated against this catalog plus base at registration.\nDefault: []'
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class RequestMediaAccessInput(BaseModel):
    """No documentation"""
    store_id: str = Field(validation_alias=AliasChoices('store_id', 'storeId'), serialization_alias='storeId')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class RequestMediaUploadInput(BaseModel):
    """No documentation"""
    original_file_name: str = Field(validation_alias=AliasChoices('original_file_name', 'originalFileName'), serialization_alias='originalFileName')
    file_size: int | None = Field(validation_alias=AliasChoices('file_size', 'fileSize'), serialization_alias='fileSize', default=None)
    content_type: str | None = Field(validation_alias=AliasChoices('content_type', 'contentType'), serialization_alias='contentType', default=None)
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ResolvedDependencyInput(BaseModel):
    """The input for mapping dependencies to implementations in a agent."""
    key: str = Field(description='The key of the dependency to map. This is used to identify the dependency in the system.')
    mapped_agents: tuple[MappedAgentInput, ...] = Field(validation_alias=AliasChoices('mapped_agents', 'mappedAgents'), serialization_alias='mappedAgents', description='The list of mapped agents to map to implementations in agents. This is used to identify the mapped agents in the system.')
    auto_resolve: Annotated[bool | None, GraphQLDefault('False')] = Field(validation_alias=AliasChoices('auto_resolve', 'autoResolve'), serialization_alias='autoResolve', default=None, description='Whether this dependency should be automatically resolved by the system. If true, the system will attempt to find a agent that can resolve this dependency and assign it to the action when the action is assigned. This is used to enable automatic resolution of dependencies without requiring the user to specify a specific agent for the dependency.')
    'Whether this dependency should be automatically resolved by the system. If true, the system will attempt to find a agent that can resolve this dependency and assign it to the action when the action is assigned. This is used to enable automatic resolution of dependencies without requiring the user to specify a specific agent for the dependency.\nDefault: False'
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ResumeInput(BaseModel):
    """The input for resuming a task."""
    task: ID = Field(description='The task ID to resume')
    step: Annotated[bool | None, GraphQLDefault('False')] = Field(default=None, description='Resume only until the next breakpoint instead of running on freely.')
    'Resume only until the next breakpoint instead of running on freely.\nDefault: False'
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ShelveInMemoryDrawerInput(BaseModel):
    """No documentation"""
    identifier: Identifier = Field(description='The identifier of the drawer. This is used to identify the drawer in the system.')
    resource_id: str = Field(validation_alias=AliasChoices('resource_id', 'resourceId'), serialization_alias='resourceId', description='The resource ID of the drawer.')
    label: str | None = Field(default=None, description='The label of the drawer. This is used to identify the drawer in the system.')
    description: str | None = Field(default=None, description='The description of the drawer. This is used to identify the drawer in the system.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ShortcutFilter(BaseModel):
    """No documentation"""
    and_: 'ShortcutFilter | None' = Field(validation_alias=AliasChoices('and_', 'AND'), serialization_alias='AND', default=None)
    or_: 'ShortcutFilter | None' = Field(validation_alias=AliasChoices('or_', 'OR'), serialization_alias='OR', default=None)
    not_: 'ShortcutFilter | None' = Field(validation_alias=AliasChoices('not_', 'NOT'), serialization_alias='NOT', default=None)
    distinct: bool | None = Field(validation_alias=AliasChoices('distinct', 'DISTINCT'), serialization_alias='DISTINCT', default=None)
    search: str | None = None
    ids: tuple[ID, ...] | None = None
    demands: tuple[PortDemandInput, ...] | None = None
    toolbox: ID | None = None
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ShortcutOrderName(BaseModel):
    """'name' variant of the @oneOf input 'ShortcutOrder'"""
    name: Ordering
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)
ShortcutOrder = ShortcutOrderName

class StrFilterLookup(BaseModel):
    """No documentation"""
    exact: str | None = None
    i_exact: str | None = Field(validation_alias=AliasChoices('i_exact', 'iExact'), serialization_alias='iExact', default=None)
    contains: str | None = None
    i_contains: str | None = Field(validation_alias=AliasChoices('i_contains', 'iContains'), serialization_alias='iContains', default=None)
    in_list: tuple[str, ...] | None = Field(validation_alias=AliasChoices('in_list', 'inList'), serialization_alias='inList', default=None)
    gt: str | None = None
    gte: str | None = None
    lt: str | None = None
    lte: str | None = None
    starts_with: str | None = Field(validation_alias=AliasChoices('starts_with', 'startsWith'), serialization_alias='startsWith', default=None)
    i_starts_with: str | None = Field(validation_alias=AliasChoices('i_starts_with', 'iStartsWith'), serialization_alias='iStartsWith', default=None)
    ends_with: str | None = Field(validation_alias=AliasChoices('ends_with', 'endsWith'), serialization_alias='endsWith', default=None)
    i_ends_with: str | None = Field(validation_alias=AliasChoices('i_ends_with', 'iEndsWith'), serialization_alias='iEndsWith', default=None)
    range: tuple[str, ...] | None = None
    is_null: bool | None = Field(validation_alias=AliasChoices('is_null', 'isNull'), serialization_alias='isNull', default=None)
    regex: str | None = None
    i_regex: str | None = Field(validation_alias=AliasChoices('i_regex', 'iRegex'), serialization_alias='iRegex', default=None)
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ToolboxFilter(BaseModel):
    """No documentation"""
    name: StrFilterLookup | None = None
    and_: 'ToolboxFilter | None' = Field(validation_alias=AliasChoices('and_', 'AND'), serialization_alias='AND', default=None)
    or_: 'ToolboxFilter | None' = Field(validation_alias=AliasChoices('or_', 'OR'), serialization_alias='OR', default=None)
    not_: 'ToolboxFilter | None' = Field(validation_alias=AliasChoices('not_', 'NOT'), serialization_alias='NOT', default=None)
    distinct: bool | None = Field(validation_alias=AliasChoices('distinct', 'DISTINCT'), serialization_alias='DISTINCT', default=None)
    ids: tuple[ID, ...] | None = None
    search: str | None = None
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class ToolboxOrderName(BaseModel):
    """'name' variant of the @oneOf input 'ToolboxOrder'"""
    name: Ordering
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)
ToolboxOrder = ToolboxOrderName

class UnshelveMemoryDrawerInput(BaseModel):
    """No documentation"""
    id: str = Field(description='The resource ID of the drawer.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)

class WidgetDefaultInput(BaseModel):
    """A catalog's default widget for ports matching a kind and/or structure identifier. A UI applies it when a port has no explicit widget; an identifier match beats a kind match."""
    kind: PortKind | None = Field(default=None, description='Port kind the default applies to. With `identifier`, both must match.')
    identifier: str | None = Field(default=None, description="Structure identifier the default applies to, e.g. '@mikro/image'.")
    widget: AssignWidgetInput | None = Field(default=None, description='The assign widget to render for matching argument ports that declare no widget of their own.')
    return_widget: ReturnWidgetInput | None = Field(validation_alias=AliasChoices('return_widget', 'returnWidget'), serialization_alias='returnWidget', default=None, description='The return widget to render for matching return ports that declare no widget of their own.')
    model_config = ConfigDict(frozen=True, extra='forbid', populate_by_name=True, use_enum_values=True)
ActionFilter.model_rebuild()
AgentFilter.model_rebuild()
AssignInput.model_rebuild()
CatalogComponentInput.model_rebuild()
CreateSpaceInput.model_rebuild()
ImplementationActionFilter.model_rebuild()
ImplementationAgentFilter.model_rebuild()
ImplementationFilter.model_rebuild()
RegisterUiCatalogInput.model_rebuild()
ShortcutFilter.model_rebuild()
ToolboxFilter.model_rebuild()